version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hospital_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital_pass
    ports:
      - "3307:3306"
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - hospital_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hospital_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hospital_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge

volumes:
  mysql_data: